---
- hosts: all
  tasks:
    - name: stop nginx
      service:
          name: nginx
          state: stopped
    - name: Nginx status
      ansible.builtin.debug:
        msg:
         - "nginx stopped successfully"
